[versions]
agp = "8.5.2"
kotlin = "1.9.24"
coroutines = "1.8.0"
ksp = "1.9.24-1.0.20"
composeBom = "2024.08.00"
accompanist = "0.34.0"
appcompat = "1.7.0"
activity = "1.9.1"
fragment = "1.8.2"
lifecycle = "2.8.4"
ktx = "1.13.1"
room = "2.6.1"
paging = "3.3.2"
recyclerview = "1.3.2"
constraintlayout = "2.1.4"
navigation = '2.7.7'
hilt = '2.50'
hiltExtension = '1.2.0'
annotations = "1.8.2"
datastore = "1.1.1"
retrofit = "2.11.0"

[libraries]
# ======================================================
# androidx
# ======================================================
# base
androidx-annotations = { module = "androidx.annotation:annotation", version.ref = "annotations" }
androidx-appcompat = { module = "androidx.appcompat:appcompat", version.ref = "appcompat" }
androidx-activity = { module = "androidx.activity:activity", version.ref = "activity" }
androidx-activity-ktx = { module = "androidx.activity:activity-ktx", version.ref = "activity" }
androidx-fragment = { module = "androidx.fragment:fragment", version.ref = "fragment" }
androidx-fragment-ktx = { module = "androidx.fragment:fragment-ktx", version.ref = "fragment" }
androidx-lifecycle-runtime-ktx = { module = "androidx.lifecycle:lifecycle-runtime-ktx", version.ref = "lifecycle" }
androidx-lifecycle-viewmodel-ktx = { module = "androidx.lifecycle:lifecycle-viewmodel-ktx", version.ref = "lifecycle" }
androidx-ktx = { module = "androidx.core:core-ktx", version.ref = "ktx" }
androidx-recyclerview = { module = "androidx.recyclerview:recyclerview", version.ref = "recyclerview" }
androidx-constraintlayout = { module = "androidx.constraintlayout:constraintlayout", version.ref = "constraintlayout" }

# paging
androidx-paging-runtime = { module = "androidx.paging:paging-runtime", version.ref = "paging" }
androidx-paging-common = { module = "androidx.paging:paging-common", version.ref = "paging" }
androidx-paging-rxjava2 = { module = "androidx.paging:paging-rxjava2", version.ref = "paging" }
androidx-paging-rxjava3 = { module = "androidx.paging:paging-rxjava3", version.ref = "paging" }

# room
androidx-room = { module = "androidx.room:room-common", version.ref = "room" }
androidx-room-ktx = { module = "androidx.room:room-ktx", version.ref = "room" }
androidx-room-guava = { module = "androidx.room:room-guava", version.ref = "room" }
androidx-room-migration = { module = "androidx.room:room-migration", version.ref = "room" }
androidx-room-runtime = { module = "androidx.room:room-runtime", version.ref = "room" }
androidx-room-rxjava = { module = "androidx.room:room-rxjava2", version.ref = "room" }
androidx-room-apt = { module = "androidx.room:room-compiler", version.ref = "room" }

# navigation
androidx-navigation-fragment-ktx = { module = "androidx.navigation:navigation-fragment-ktx", version.ref = "navigation" }
androidx-navigation-ui-ktx = { module = "androidx.navigation:navigation-ui-ktx", version.ref = "navigation" }

# data store
androidx-datastore-core = { module = "androidx.datastore:datastore-core", version.ref = "datastore" }
androidx-datastore-sp = { module = "androidx.datastore:datastore-preferences", version.ref = "datastore" }

# hilt
google-hilt = { module = "com.google.dagger:hilt-android", version.ref = "hilt" }
google-hilt-compiler = { module = "com.google.dagger:hilt-android-compiler", version.ref = "hilt" }
google-ui-material = "com.google.android.material:material:1.12.0"

# ======================================================
# kotlin
# ======================================================
# kotlin core
kotlin-stdlib = { module = "org.jetbrains.kotlin:kotlin-stdlib", version.ref = "kotlin" }
kotlin-reflect = { module = "org.jetbrains.kotlin:kotlin-reflect", version.ref = "kotlin" }
kotlinx-coroutines = { module = "org.jetbrains.kotlinx:kotlinx-coroutines-core", version.ref = "coroutines" }

# ======================================================
# compose
# ======================================================
# what is bom: https://developer.android.com/develop/ui/compose/bom
# BOM to library version mapping: https://developer.android.com/develop/ui/compose/bom/bom-mapping
compose-bom = { group = "androidx.compose", name = "compose-bom", version.ref = "composeBom" }

# compose ui 基础
compose-ui = { module = "androidx.compose.ui:ui" }
compose-ui-graphics = { module = "androidx.compose.ui:ui-graphics" }
compose-ui-tooling-preview = { module = "androidx.compose.ui:ui-tooling-preview" }
compose-animation = { module = "androidx.compose.animation:animation" }
compose-animation-core = { module = "androidx.compose.animation:animation-core" }
compose-animation-graphics = { module = "androidx.compose.animation:animation-graphics" }
compose-ui-constraint = "androidx.constraintlayout:constraintlayout-compose:1.0.1"

# compose material3
compose-material3 = { module = "androidx.compose.material3:material3" }
compose-material3-window-size = { module = "androidx.compose.material3:material3-window-size-class" }
compose-material-icon-extended = { module = "androidx.compose.material:material-icons-extended" }

# integration with viewmodels, hilt and navigation
compose-livedata = { module = "androidx.compose.runtime:runtime-livedata" }
compose-activity = { module = "androidx.activity:activity-compose", version.ref = "activity" }
compose-viewmodel = { module = "androidx.lifecycle:lifecycle-viewmodel-compose", version.ref = "lifecycle" }
compose-navigation = { module = "androidx.navigation:navigation-compose", version.ref = "navigation" }
compose-hilt-navigation = { module = "androidx.hilt:hilt-navigation-compose", version.ref = "hiltExtension" }
compose-lifecycle-android = { module = "androidx.lifecycle:lifecycle-runtime-compose-android", version.ref = "lifecycle" }
compose-paging-android = { module = "androidx.paging:paging-compose-android", version.ref = "paging" }

# compose ui tool (debugImplementation)
compose-ui-tooling = { module = "androidx.compose.ui:ui-tooling" }
compose-ui-test-manifest = { module = "androidx.compose.ui:ui-test-manifest" }

# accompanist: https://github.com/google/accompanist
compose-accompanist-permission = { module = "com.google.accompanist:accompanist-permissions", version.ref = "accompanist" }
compose-accompanist-drawablepainter = { module = "com.google.accompanist:accompanist-drawablepainter", version.ref = "accompanist" }
compose-accompanist-adaptive = { module = "com.google.accompanist:accompanist-adaptive", version.ref = "accompanist" }

# ======================================================
# functional libraries
# ======================================================
ztiany-uistate = "com.github.Ztiany:android-ui-state:1.0.5"
ztiany-simplehttp = "com.github.Ztiany:android-simple-http:1.2.3"
# https://github.com/coil-kt/coil
coil-compose = "io.coil-kt:coil-compose:2.6.0"
# https://github.com/JakeWharton/timber
jakewharton-timber = "com.jakewharton.timber:timber:5.0.1"
# https://github.com/guolindev/PermissionX
guolin-permissionx = "com.guolindev.permissionx:permissionx:1.8.0"
# https://github.com/square/okhttp
square-okhttp = "com.squareup.okhttp3:okhttp:4.12.0"
square-okhttp-logging = "com.squareup.okhttp3:logging-interceptor:4.12.0"
# https://github.com/square/retrofit
square-retrofit = { module = "com.squareup.retrofit2:retrofit", version.ref = "retrofit" }
square-retrofit-converter-gson = { module = "com.squareup.retrofit2:converter-gson", version.ref = "retrofit" }
# https://github.com/google/gson/blob/master/UserGuide.md#TOC-Overview
google-gson = "com.google.code.gson:gson:2.11.0"

[plugins]
# ======================================================
# official plugins
# ======================================================
android-application = { id = "com.android.application", version.ref = "agp" }
android-library = { id = "com.android.library", version.ref = "agp" }
google-hilt = { id = "com.google.dagger.hilt.android", version.ref = "hilt" }
google-ksp = { id = "com.google.devtools.ksp", version.ref = "ksp" }
jetbrains-kotlin-android = { id = "org.jetbrains.kotlin.android", version.ref = "kotlin" }
jetbrains-kotlin-kapt = { id = "org.jetbrains.kotlin.kapt", version.ref = "kotlin" }
jetbrains-kotlin-parcelize = { id = "org.jetbrains.kotlin.plugin.parcelize", version.ref = "kotlin" }
androidx-navigation-safeargs-kotlin = { id = "androidx.navigation.safeargs.kotlin", version.ref = "navigation" }